name: appodeal_flutter
description: A Flutter plugin to display ads from Appodeal; it supports the new reqs for iOS 14+ and GDPR/CCPA consent.
version: 0.2.3
homepage: https://github.com/vegidio-flutter/appodeal

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.vinicius.appodeal_flutter
        pluginClass: AppodealFlutterPlugin
      ios:
        pluginClass: AppodealFlutterPlugin